// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// DataHandler is an autogenerated mock type for the DataHandler type
type DataHandler struct {
	mock.Mock
}

type DataHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *DataHandler) EXPECT() *DataHandler_Expecter {
	return &DataHandler_Expecter{mock: &_m.Mock}
}

// GetDB provides a mock function with given fields: ctx
func (_m *DataHandler) GetDB(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// DataHandler_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type DataHandler_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataHandler_Expecter) GetDB(ctx interface{}) *DataHandler_GetDB_Call {
	return &DataHandler_GetDB_Call{Call: _e.mock.On("GetDB", ctx)}
}

func (_c *DataHandler_GetDB_Call) Run(run func(ctx context.Context)) *DataHandler_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DataHandler_GetDB_Call) Return(_a0 *gorm.DB) *DataHandler_GetDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataHandler_GetDB_Call) RunAndReturn(run func(context.Context) *gorm.DB) *DataHandler_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *DataHandler) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataHandler_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DataHandler_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DataHandler_Expecter) Ping(ctx interface{}) *DataHandler_Ping_Call {
	return &DataHandler_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *DataHandler_Ping_Call) Run(run func(ctx context.Context)) *DataHandler_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DataHandler_Ping_Call) Return(_a0 error) *DataHandler_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataHandler_Ping_Call) RunAndReturn(run func(context.Context) error) *DataHandler_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RunTransaction provides a mock function with given fields: ctx, fc
func (_m *DataHandler) RunTransaction(ctx context.Context, fc func(context.Context) error) error {
	ret := _m.Called(ctx, fc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DataHandler_RunTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTransaction'
type DataHandler_RunTransaction_Call struct {
	*mock.Call
}

// RunTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fc func(context.Context) error
func (_e *DataHandler_Expecter) RunTransaction(ctx interface{}, fc interface{}) *DataHandler_RunTransaction_Call {
	return &DataHandler_RunTransaction_Call{Call: _e.mock.On("RunTransaction", ctx, fc)}
}

func (_c *DataHandler_RunTransaction_Call) Run(run func(ctx context.Context, fc func(context.Context) error)) *DataHandler_RunTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *DataHandler_RunTransaction_Call) Return(_a0 error) *DataHandler_RunTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataHandler_RunTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *DataHandler_RunTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewDataHandler creates a new instance of DataHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataHandler {
	mock := &DataHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
